spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Tempo@0900
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        enable_lazy_load_no_trans: true
    open-in-view: true

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR
    com.alura: INFO